name:        exotic-list-monads
synopsis:    Non-standard monads on lists and non-empty lists
description: The usual list monad is only one of infinitely many ways to turn the list functor into a monad. The same applies to the usual non-empty list monad and the non-empty list functor. This library collects such non-standard "list" and "non-empty list" monads.
version:     1.1.0
license:     MIT
copyright:   (c) 2020 Dylan McDermott, Maciej Piróg, Tarmo Uustalu
author:      Maciej Piróg <maciej.adam.pirog@gmial.com>
maintainer:  Maciej Piróg <maciej.adam.pirog@gmail.com>
category:    List, Monads
github:      maciejpirog/exotic-list-monads
homepage:    http://github.com/maciejpirog/exotic-list-monads
bug-reports: http://github.com/maciejpirog/exotic-list-monads/issues

extra-source-files:
  - README.md
  - CHANGELOG.md
  - degrading-lists.pdf

ghc-options:
 -Wall
 -Wno-name-shadowing
 -fno-warn-partial-type-signatures

dependencies:
 - base >= 4.9 && < 5

tested-with: GHC ==8.10.3

library:
  source-dirs: src

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies:
      - exotic-list-monads
      - QuickCheck
      - hspec-core
